### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by fruitofgeorge** [w0lfschild/mySIMBL#114]
I can't find any instructions anywhere of how to use this app. I just want to use the spotifyplus plugin. It shows up in the manage tab but I can't figure out how to configure any options or get it work as ads are still playing. Every time I launch mysimbl it says it needs to "update components" (sounds sketchy, what exactly is it updating?) so I enter the password each time but nothing happens and apparently it doesn't update because it will ask me again the next time I launch.
Another annoying design bug, the window for the app always stays in the front even when not active and prevents me from seeing other windows when I click over to a different app.

**Comment by fruitofgeorge** [comment]
Just realized latest commit >7 months ago. Guess I'll move on to something being maintained.

**Comment by sancarn** [comment]
I’m not the maintainer but FWIW 7 months old is more maintained than a lot of repos on here lol

**Comment by fruitofgeorge** [comment]
Sure, when you have something stable but not when you have bugs that make it inoperable that were reported greater than those 7 months ago.

**Comment by w0lfschild** [comment]
I think the issue is likely something to do with permissions but hard for me to tell without more info.

Update components just means it needs to install some helper files in `/Library`

There haven't really been any updates to this because for the most part it is still working and I'm just one dude that makes no money from this project so I only work on it when I can.

The controls for spotify+ are supposed to show up in spotify but really the ad blocking is just editing the hosts file, which unfortunately with recent versions of spotify prevents some songs from playing or showing up altogether in spotify.

![Screen Shot 2019-06-18 at 11 29 24 AM](https://user-images.githubusercontent.com/1920148/59709772-5c4dea00-91bc-11e9-8f55-3e0815652fa5.png)

**Comment by fruitofgeorge** [comment]
Ah, my hosts file started causing issues with spotify which is why I went looking for another solution. Thanks for the response.
