### ISSUE TITLE
mySIMBLAgent - Crash on launch

### ISSUE THREAD

**Issue by drewauff** [w0lfschild/mySIMBL#12]
Process:               mySIMBLAgent [832]
Path:                  /Users/USER/*/mySIMBL.app/Contents/Library/LoginItems/mySIMBLAgent.app/Contents/MacOS/mySIMBLAgent
Identifier:            mySIMBLAgent
Version:               0.2.1 (4)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           mySIMBLAgent [832]
User ID:               501

Date/Time:             2016-12-18 14:23:15.213 +1100
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12
Anonymous UUID:        D0D7F2C3-E034-6896-A131-92A810F92B83

Time Awake Since Boot: 140 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/USER/*/mySIMBL.app/Contents/Library/LoginItems/mySIMBLAgent.app/Contents/MacOS/mySIMBLAgent
  Reason: image not found

Binary Images:
       0x10feef000 -        0x10fef3ff7 +org.w0lf.mySIMBLAgent (0.2.1 - 4) <AD4091CF-8780-3EBA-AF81-4DE1B2245704> /Users/USER/*/mySIMBL.app/Contents/Library/LoginItems/mySIMBLAgent.app/Contents/MacOS/mySIMBLAgent
       0x11d52a000 -        0x11d567287  dyld (421.2) <13A9466A-2576-3ABB-AD9D-D6BC16439B8F> /usr/lib/dyld

Model: MacBookPro10,1, BootROM MBP101.00EE.B0A, 4 processors, Intel Core i7, 2.7 GHz, 16 GB, SMC 2.3f36
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Graphics: NVIDIA GeForce GT 650M, NVIDIA GeForce GT 650M, PCIe, 1024 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xEF), Broadcom BCM43xx 1.0 (7.21.171.47.1a8)
Bluetooth: Version 5.0.1f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM768E, 751.28 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 23.4

**Comment by KJI** [comment]
Also constant crashes after the update !
Process:               mySIMBLAgent [15353]
Path:                  /Applications/mySIMBL.app/Contents/Library/LoginItems/mySIMBLAgent.app/Contents/MacOS/mySIMBLAgent
Identifier:            mySIMBLAgent
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           mySIMBLAgent [15353]
User ID:               501

Date/Time:             2016-12-18 12:51:39.401 +0100
OS Version:            Mac OS X 10.11.6 (15G1212)
Report Version:        11
Anonymous UUID:        E3D5750D-F25F-78EA-44D9-153DB4F43911


Time Awake Since Boot: 100000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Applications/mySIMBL.app/Contents/Library/LoginItems/mySIMBLAgent.app/Contents/MacOS/mySIMBLAgent
  Reason: image not found

Binary Images:
    0x7fff68c9f000 -     0x7fff68cd6a47  dyld (360.22) <884763FC-CC0F-31CC-ACC4-75A805CE401D> /usr/lib/dyld

Model: iMac17,1, BootROM IM171.0105.B08, 4 processors, Intel Core i7, 4 GHz, 16 GB, SMC 2.33f10
Graphics: AMD Radeon R9 M390, AMD Radeon R9 M390, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x484D54343147533642465238412D52442020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x484D54343147533642465238412D52442020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x14A), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
Bluetooth: Version 4.4.6f1 17910, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
PCI Card: pci11c1,5901, IEEE 1394 Open HCI, Thunderbolt@195,0,0
Serial ATA Device: APPLE SSD SM0128G, 121.33 GB
Serial ATA Device: APPLE HDD ST2000DM001, 2 TB
USB Device: USB 3.0 Bus
USB Device: USB3.0 Hub
USB Device: USB2.0 Hub
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Datacolor Spyder5
USB Device: Keyboard Hub
USB Device: ELECOM Scope Node Mouse
USB Device: Apple Keyboard
FireWire Device: unknown_device, Unknown
Thunderbolt Bus: iMac, Apple Inc., 28.1
Thunderbolt Device: Thunderbolt to FireWire Adapter, Apple Inc., 3, 5.6

**Comment by JayBrown** [comment]
Same here:

```
Process:               mySIMBLAgent [2833]
Path:                  /Applications/mySIMBL.app/Contents/Library/LoginItems/mySIMBLAgent.app/Contents/MacOS/mySIMBLAgent
Identifier:            mySIMBLAgent
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           mySIMBLAgent [2833]
User ID:               501

Date/Time:             2016-12-18 14:35:33.968 +0100
OS Version:            Mac OS X 10.11.6 (15G1212)
Report Version:        11
Anonymous UUID:        1DC10151-895F-DE52-8CD9-3BEFCAC7E8E8


Time Awake Since Boot: 1200 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Applications/mySIMBL.app/Contents/Library/LoginItems/mySIMBLAgent.app/Contents/MacOS/mySIMBLAgent
  Reason: image not found

Binary Images:
    0x7fff678f6000 -     0x7fff6792da47  dyld (360.22) <884763FC-CC0F-31CC-ACC4-75A805CE401D> /usr/lib/dyld

Model: MacBookPro6,2, BootROM MBP61.0057.B11, 2 processors, Intel Core i7, 2,66 GHz, 8 GB, SMC 1.58f17
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe, 512 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353237334348302D4346382020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353237334348302D4346382020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.100.24)
Bluetooth: Version 4.4.6f1 17910, 3 services, 27 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Network Service: Parallels Shared Networking Adapter #0, Ethernet, vnic0
Serial ATA Device: ST9500420ASG, 500,11 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: IR Receiver
USB Device: Built-in iSight
Thunderbolt Bus: 
```

**Comment by JayBrown** [comment]
Addendum: Re-installing v0.4.1 over the previous buggy v0.4.1 didn't change anything.

**POSSIBLE SOLUTIONS**

(1) Revert back to v0.3.1; worked in my case.

(2) Stick with v0.4.1, but copy the Sparkle framework v1.14.0 which you can find in mySIMBL v0.3.1 at the path `./mySIMBL.app/Contents/Frameworks/Sparkle.framework`, and replace the newer Sparkle framework 1.15.1 in v0.4.1 at the standard path `/Applications/mySIMBL.app/Contents/Frameworks/Sparkle.framework`. The error messages & crashes immediately stopped for me.

**Comment by w0lfschild** [comment]
Thanks for the heads up folks. 👍

Try 0.4.2, I forgot to update the framework search path for the agent since it was moved from `/Contents/Resources` to `/Contents/Library/LoginItems`.

**Comment by drewauff** [comment]
awesome thanks 👍
